### ISSUE TITLE
Install Instructions

### ISSUE THREAD

**Issue by henfri** [bpereto/borg-hive#12]
Hello,

thanks for sharing borg-hive.
It would be good, if you could add install instructions to Readme.md.

Regards,
Hendrik

**Comment by ikkemaniac** [comment]
I found some docs in the docs folder, quickstart should get you going but i'm having a hard time getting it fully functional.

**Comment by bpereto** [comment]
Yes, they should be improved / added.
Currently some information is as already mentioned on Quickstart: https://borg-hive.readthedocs.io/en/latest/quickstart.html

**Comment by bpereto** [comment]
* Added section "installation" to the documentation
* Added Documentation about deployment to k8s with helm
* Linked "Quickstart" Documentation in the Readme

ikkemaniac has already fixed some setup issues and added hints to the documentation. please open a new issue regarding some specific topics for documentation or improvement.
