### ISSUE TITLE
Remote Repositories

### ISSUE THREAD

**Issue by henfri** [bpereto/borg-hive#33]
Hello,

I have some repositories locally, but also some that are reachable via a remote borg instance.
Will these also be visible in borg-hive?

Regards,
Hendrik

**Comment by bpereto** [comment]
you can think of hosting borg repositories in borg-hive. as per design, you have to create repositories within borg-hive, which you then can access and backup to. from borgbackup client view it's always a remote repository.

I haven't made thoughts about migrating existing repositories to borg-hive yet. there is also an issue open to extend the borg-hive documentation regarding the description of the architecture, which should clarify the possibilities with borg-hive. #20

**Comment by henfri** [comment]
Hello,

>  as per design, you have to create repositories within borg-hive, which you then can access and backup to. from borgbackup client view it's always a remote repository.

It would be good, if one would not be 'locked in' borg-hive. 
Of course I do not know the architecture, thus I do not see the reason, why it is not possible to just load an existing backup?

Regards,
Hendrik

**Comment by bpereto** [comment]
> It would be good, if one would not be 'locked in' borg-hive.

there is no 'lock-in'. you ca always access and export the data via borgbackup. If you self-host, then you can always access the docker volume and copy the data.

>  why it is not possible to just load an existing backup?

borg-hive expects some internal structure on the filesystem. a user is generated for each created repository (https://borg-hive.readthedocs.io/en/latest/internals.html#repository-user) on the FS, LDAP and DB.

With the current functionality of the  project, a workaround is to create a new repository in borg-hive and overwrite it. copy the wanted "import"-repository manually to the correct path on the filesystem with the correct permissions and ownerships in the docker volume. this is a little bit fiddly and there is much room for errors. 

If you want to contribute: I'm open for ideas how this could be technically solved. I don't know if its a good idea to enable an SSH-Shell for rsync and scp.

**Comment by bpereto** [comment]
borg repository import / export mechanism implemented by #38
