### ISSUE TITLE
Manage existing repos

### ISSUE THREAD

**Issue by Bouni** [bpereto/borg-hive#56]
Hi,

it is not clear (at least to me after searching the docs) if borg-hive can be used to manage existing backups!?

At the moment I use borgmatic (locally installed on my machine) to backup my stuff to my server.
I backup stuff from the server also with borgmatic to another disk of the same server (I know, not the best idea 😅 )
Now I want to run borg-hive on the server as well and have it manageing my backups.

Is that even possible or do I have to setup everything from scratch to use borg-hive?

**Comment by bpereto** [comment]
hi,

borg-hive does a little bit more, than just a webui for borg repositories. 

borg-hive expects some internal structure on the filesystem. a user is generated for each created repository (https://borg-hive.readthedocs.io/en/latest/internals.html#repository-user) on the FS, LDAP and DB. The access is managed by configuring some SSH-Keys, which you have to specify.

There is an option to import (or even export) an existing borg archive:
https://borg-hive.readthedocs.io/en/latest/usage.html#import-or-export-existing-repositories

So yeah, you must setup a new repository in borg-hive, adjust your borgmatic configuration and you can optionally import/migrate your existing archive into borg-hive.

**Comment by Bouni** [comment]
Ok, thanks for the explanation!
I'll see if I manage to do that or stick with borgmatic 🤔
