### ISSUE TITLE
Hive backup

### ISSUE THREAD

**Issue by Firesphere** [bpereto/borg-hive#65]
Is it possible to backup the Hive itself? I can't find where/what I should backup to keep the settings and SSH keys I've entered, etc.

**Comment by bpereto** [comment]
Hi, 

yes, this is missing in the documentation.
the important settings are in the sql database (sshkeys, repository, webhooks etc.) and associated user in the ldap server.

so the documentation should have a section mentioning how to backup:
* sql database
* ldap data

the backup of the sql database is rather easy, as borg-hive itself is using the django framework, so executing a command in the web container:
```
manage.py dumpdata
```

or executing a command in the mariadb database container to dump the database directly with tools provided by mariadb.

**Comment by Firesphere** [comment]
Thanks,

I'll have a play around, and write some documentation if I get to it and get it working :)

**Comment by Firesphere** [comment]
See PR I added for OpenLDAP backup.

I'll probably make a separate PR around MariaDB backup (which is very straight forward, thankfully) and how to backup-and-restore the "old" version that does not have the backupping container
