### ISSUE TITLE
Email notifications

### ISSUE THREAD

**Issue by Firesphere** [bpereto/borg-hive#66]
Where can I configure the email notifications SMTP server? It seems unwilling to email at the moment.

**Comment by bpereto** [comment]
Hi,

set a valid SMTP Server and SMTP authentication with the environment variables:
(additionally the email backend [django.core.mail.backends.smtp.EmailBackend](https://docs.djangoproject.com/en/4.0/ref/settings/#std:setting-EMAIL_BACKEND) when running in debug mode) - so i recommend to disable the debug mode if you are testing, as its a dummy backend which does nothing.

https://github.com/bpereto/borg-hive/blob/master/src/core/settings.py
```
#
# NOTIFICATION SETTINGS
#
EMAIL_HOST = env('EMAIL_HOST', 'localhost')
EMAIL_PORT = env('EMAIL_PORT', '465')
EMAIL_HOST_USER = env('EMAIL_HOST_USER', 'root')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', 'password')
EMAIL_USE_SSL = True  # disallow unsecure communication!
EMAIL_FROM = env('EMAIL_FROM', 'borghive@{}'.format(socket.getfqdn()))
if DEBUG:
    EMAIL_BACKEND = env('EMAIL_BACKEND', 'django.core.mail.backends.dummy.EmailBackend')
 ```

then add a email notification in borg-hive.

**Comment by Firesphere** [comment]
Hi @bpereto ,

It was an error on my side, which I discovered very late last night (my time), and haven't gotten back to you yet.
The email server didn't accept the email FROM, as it was not a known email address.

May be of reference for others: The mail server you use might want a valid, existing email address before it sends out.
